--
-- PostgreSQL database dump
--

\restrict Lq66ZUQL5gABKjjmb1OFZHpNpuIcxsAfrOyMUL4Id3kUWURtJYKZKtuzOmBDN5F

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg110+2)
-- Dumped by pg_dump version 16.12 (Ubuntu 16.12-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: indicators; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (2, 'Households/HouseholdsEnumeratedAgainstTarget', 'households.households-enumerated-against-target', '{"en": "Households enumerated against target"}', '{"en": "Households enumerated against target"}', '{"en": null}', 'households', true, 'Default', NULL, NULL, '[{"meta": {"columnNames": {"x": "area_name", "y": "ref_value"}}, "mode": "lines", "name": "Reference", "type": "bar", "xsrc": "area_name", "ysrc": "ref_value", "orientation": "v"}, {"meta": {"columnNames": {"x": "area_name", "y": "household"}}, "mode": "markers", "name": "Actual", "type": "bar", "xsrc": "area_name", "ysrc": "household", "orientation": "v"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 187106.31578947368], "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "barmode": "overlay", "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-08 12:07:35', '2026-01-23 06:32:17', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (3, 'Households/PopulationPyramid', 'households.population-pyramid', '{"en": "Population pyramid"}', '{"en": "Population pyramid"}', '{"en": null}', 'households', true, 'Default', NULL, '2026-01-23 06:32:45', '[{"meta": {"columnNames": {"x": "males_negated", "y": "age_range"}}, "mode": "markers", "name": "Males", "type": "bar", "xsrc": "males_negated", "ysrc": "age_range", "orientation": "h"}, {"meta": {"columnNames": {"x": "females", "y": "age_range"}}, "name": "Females", "type": "bar", "xsrc": "females", "ysrc": "age_range", "orientation": "h"}]', '{"xaxis": {"type": "linear", "range": [-334692.77777777775, 328262.77777777775], "tickmode": "auto", "autorange": true, "automargin": true, "showticklabels": false}, "yaxis": {"type": "category", "range": [-0.5, 24.5], "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "barmode": "relative", "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-08 12:45:11', '2026-01-23 06:32:45', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (9, 'Households/MaleToFemaleRatio', 'households.male-to-female-ratio', '{"en": "Male to female ratio"}', '{"en": "Male to female ratio"}', '{"en": null}', 'households', true, 'Default', NULL, NULL, '[{"meta": {"columnNames": {"x": "area_name", "y": "ratio"}}, "mode": "markers", "name": "Males per 100 females", "type": "bar", "xsrc": "area_name", "ysrc": "ratio", "orientation": "v"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 125.90253171812058], "title": {"text": "Number of males per 100 females"}, "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-10 12:15:39', '2026-01-23 06:32:29', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (4, 'Households/AverageInterviewTime', 'households.average-interview-time', '{"en": "Average interview time"}', '{"en": "Average interview time"}', '{"en": null}', 'households', true, 'Default', NULL, NULL, '[{"meta": {"columnNames": {"x": "area_name", "y": "average"}}, "mode": "markers", "name": "Average interview time", "type": "bar", "xsrc": "area_name", "ysrc": "average", "orientation": "v"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "title": {"text": "Counties"}, "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 40.315789473684205], "title": {"text": "Average interview time (minutes)"}, "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-09 11:04:19', '2026-01-23 06:21:05', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (5, 'Households/BirthRate', 'households.birth-rate', '{"en": "Birth rate"}', '{"en": "Birth rate"}', '{"en": null}', 'households', true, 'Default', NULL, NULL, '[{"meta": {"columnNames": {"x": "area_name", "y": "rate"}}, "mode": "markers", "name": "Crude birth rate per 1000 population", "type": "bar", "xsrc": "area_name", "ysrc": "rate", "orientation": "v"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 34.19636744247734], "title": {"text": "Birth rate"}, "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-09 11:23:18', '2026-01-23 06:32:12', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (8, 'Households/HouseholdsEnumeratedAgainstTargetByDay', 'households.households-enumerated-against-target-by-day', '{"en": "Households enumerated against target by day"}', '{"en": "Households enumerated against target by day"}', '{"en": null}', 'households', false, 'Default', NULL, NULL, '[]', '{"xaxis": {"type": "category", "tickmode": "auto", "automargin": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "dragmode": "pan", "showlegend": true}', '2024-09-10 12:06:56', '2026-01-23 06:32:23', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (11, 'Households/PopulationDistributionByBroadAgeGroup', 'households.population-distribution-by-broad-age-group', '{"en": "Population distribution by broad age group"}', '{"en": "Population distribution by broad age group"}', '{"en": null}', 'households', true, 'Default', NULL, '2026-01-23 06:32:40', '[{"meta": {"columnNames": {"x": "area_name", "y": "less_than_15_percentage"}}, "mode": "markers", "name": "< 15", "type": "bar", "xsrc": "area_name", "ysrc": "less_than_15_percentage", "hoverinfo": "y+name", "orientation": "v", "texttemplate": "%{value:.1f}", "hovertemplate": null}, {"meta": {"columnNames": {"x": "area_name", "y": "between_15_and_65_percentage"}}, "name": "15 to 64", "type": "bar", "xsrc": "area_name", "ysrc": "between_15_and_65_percentage", "orientation": "v", "texttemplate": "%{value:.1f}"}, {"meta": {"columnNames": {"x": "area_name", "y": "above_and_65_percentage"}}, "name": "65+", "type": "bar", "xsrc": "area_name", "ysrc": "above_and_65_percentage", "orientation": "v", "texttemplate": "%{value:.1f}"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 100.00000000000001], "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "barmode": "stack", "barnorm": "percent", "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-10 13:52:03', '2026-01-23 06:32:40', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (1, 'Households/AverageHouseholdSize', 'households.average-household-size', '{"en": "Average household size"}', '{"en": "Average household size"}', '{"en": null}', 'households', true, 'Default', NULL, NULL, '[{"meta": {"columnNames": {"x": "area_name", "y": "average"}}, "mode": "markers", "name": "Average household size", "type": "bar", "xsrc": "area_name", "ysrc": "average", "orientation": "v"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 7.157894736842105], "title": {"text": "Household size"}, "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-08 11:18:12', '2026-01-23 06:20:50', 'Pages only') ON CONFLICT DO NOTHING;
INSERT INTO public.indicators (id, name, slug, title, description, help, data_source, published, type, tag, featured_at, data, layout, created_at, updated_at, scope) VALUES (10, 'Households/PercentagePopulationEnumeratedAgainstTarget', 'households.percentage-population-enumerated-against-target', '{"en": "Percentage of population enumerated against target"}', '{"en": "Percentage of population enumerated against target"}', '{"en": null}', 'households', true, 'Default', NULL, NULL, '[{"meta": {"columnNames": {"x": "area_name", "y": "proportion"}}, "mode": "markers", "name": "Percentage of population enumerated against target", "type": "bar", "xsrc": "area_name", "ysrc": "proportion", "orientation": "v"}]', '{"xaxis": {"type": "category", "range": [-0.5, 46.5], "tickmode": "auto", "autorange": true, "automargin": true}, "yaxis": {"type": "linear", "range": [0, 5.578947368421052], "title": {"text": "%"}, "autorange": true}, "legend": {"x": 0, "y": 1.12, "orientation": "h"}, "mapbox": {"style": "open-street-map"}, "margin": {"b": 40, "l": 60, "r": 10, "t": 10}, "modebar": {"color": "white", "bgcolor": "darkgray", "orientation": "v"}, "autosize": true, "colorway": ["#ef4444", "#eab308", "#22c55e", "#3b82f6", "#ec4899", "#a855f7", "#a1a1aa", "#166534", "#1e40af", "#6b21a8", "#000", "#ea580c", "#65a30d", "#0891b2", "#7c3aed", "#f43f5e", "#0ea5e9"], "dragmode": "pan", "showlegend": true}', '2024-09-10 13:17:10', '2026-01-23 06:32:35', 'Pages only') ON CONFLICT DO NOTHING;


--
-- Name: indicators_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.indicators_id_seq', 11, true);


--
-- PostgreSQL database dump complete
--

\unrestrict Lq66ZUQL5gABKjjmb1OFZHpNpuIcxsAfrOyMUL4Id3kUWURtJYKZKtuzOmBDN5F

